version: '3'
services:
    mysql:
        container_name: mysql 
        image: mysql:8.0.2
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: twitterdb
        ports:
            - "3306:3306"
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/config-file.cnf
            - ./mysql_data:/var/lib/mysql:rw    
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
        volumes:
            - ./var/run/docker.sock:/var/run/docker.sock    
    spark:
        container_name: pyspark-notebook
        image: jupyter/pyspark-notebook
        ports:
            - "8888:8888"
        volumes:
            - ./work:/home/jovyan/work
    
    